buildscript {
  dependencies {
    // This resolves to the gradle-plugin artifact generated by the included build.
    // Now that it's in the build classpath, it can be applied by its ID in subprojects.
    classpath("com.squareup.anvil:gradle-plugin")
  }
}

plugins {
  id("java-base")
  alias(libs.plugins.agp.application) apply false
  alias(libs.plugins.agp.library) apply false
  alias(libs.plugins.gradlePublish) apply false
  alias(libs.plugins.kotlin.android) apply false
  alias(libs.plugins.kotlin.jvm) apply false
  alias(libs.plugins.kotlin.kapt) apply false
  alias(libs.plugins.kotlin.multiplatform) apply false
  id("conventions.root")
  id("com.squareup.anvil") apply false
}
